config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path:       '',
             controllers: { invitations: 'users/invitations' },
             path_names: {
               sign_in:      'login',
               sign_out:     'logout',
               password:     'secret',
               confirmation: 'verification',
               unlock:       'unblock',
             }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    post 'users/:id/reactivate_user' => 'users#reactivate_user', as: :reactivate_user
    post 'users/:id/send_reset_password_instructions' => 'users#send_reset_password_instructions', as: :send_reset_password_instructions
    get 'reactivate_user'
    resources :mentors do
      get :track_mentor_time, controller: 'time_trackings'
    end
    post 'mentors/:id/reactivate_mentor' => 'mentors#reactivate_mentor', as: :reactivate_mentor
    get 'reactivate_mentor'
    resources :admins
    post 'admins/:id/reactivate_admin' => 'admins#reactivate_admin', as: :reactivate_admin
    get 'reactivate_admin'
    resources :clients
    post 'clients/:id/reactivate_client' => 'clients#reactivate_client', as: :reactivate_client
    get 'reactivate_client'
    resources :tags
    resources :companies do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
      resources :time_trackings, only: :index, path: 'time-tracker'
    end
    resources :checklists
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :logs, only: :index

    get :track_company_time, controller: 'time_trackings'
    root 'companies#index'
  end

  namespace :mentor do
    root 'companies#index'
    resources :companies, only: [:index, :show] do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
    end
    resources :phases
    resources :milestones
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :time_trackings, only: [:index, :new, :create], path: 'time-tracker'
  end

  namespace :member do
    root 'dashboard#show'
    resources :companies, path: 'company', only: :show
    resources :clients
    resources :company_phases
    resources :milestones, except: [:index, :create, :new, :show, :edit, :update, :destroy] do
      put :mark_complete
      put :mark_incomplete
    end
    resources :company_tasks, only: [] do
      member do
        put :mark_complete
        put :mark_incomplete
      end
    end
  end
  resources :messages
end

app/models/client.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  phone                  :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  deleted_at             :datetime
#  type                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :bigint(8)
#  invitations_count      :integer          default(0)
#

class Client < User
  has_one :client_info, dependent: :destroy
  has_many :time_trackings

  accepts_nested_attributes_for :client_info

  after_create_commit :create_client_info

  private

  def create_client_info
    ClientInfo.create(client: self) if client_info.nil?
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::UsersController
  before_action :set_client, only: [:edit, :update]

  def new
    @client = Client.new
    @client.build_client_info
  end

  def create
    @client = Client.new(client_params)
    @client.skip_password_validation = true
    if @client.valid?
      @client.save
      @client.invite!(current_user)
      redirect_to(admin_users_path, notice: 'Client was successfully created.')
    else
      render action: :new
    end
  end

  def edit; end

  def update
    if @client.update(client_params)
      redirect_to(admin_users_path, notice: 'Client was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.soft_delete
    redirect_to admin_users_path, notice: "Client deleted."
  end

  def reactivate_client
    @user = User.find(params[:id])
    @user.update_attribute(:deleted_at, nil)
    flash[:notice] = "Client Activated succesfully"
    redirect_to admin_users_path
  end

  private

  def set_client
    @client ||= Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(user_params, client_info_attributes: [:id, :description, :company_id])
  end
end

app/controllers/member/clients_controller.rb
class Member::ClientsController < Member::MemberBaseController

  before_action :set_company

  def index
    @clients = @company.clients
  end

  def new
    @client = Client.new
    @client.build_client_info()
  end

  def create
    @client = Client.new(client_params)
    if params[:client][:email].present? && params[:client][:name].present?
      @client.save(validate: false)
      @client.client_info.update_attributes(company_id: @company.id)
      @client.invite!(current_user)
      redirect_to(member_clients_path, notice: 'Client was successfully invited.')
    else
      render action: :new
    end
  end

  private

  def set_company
    @company = current_user.client_info.company
  end

  def client_params
    params.require(:client).permit(user_params, client_info_attributes: [:id, :description, :company_id])
  end
end

app/views/admin/clients/_client_list.html.haml
.container.container-content
  %table.table.table-borderless.table-responsive-sm
    %thead.thead
      %tr
        %th{:scope => "col"} 
          %h6 Name
        %th{:scope => "col"} 
          %h6 Email
        %th{:scope => "col"} 
          %h6 Company
        %th{:scope => "col"} 
          %h6 Phone
        %th{:scope => "col"} 
          %h6 Actions
    %tbody
      - @clients.each do |client|
        %tr{ class: "#{disabled_user(client.deleted_at)}" }
          %td
            = client.name if client.name.present?
          %td
            = client.email
            = " (Invitation pending)" if client.invitation_created_at.present? && client.invitation_accepted_at.nil?
          %td
            = link_to( client.client_info.company.name, admin_company_company_phase_path(client.client_info.company, client.client_info.company.current_phase))
          %td
            = client.phone if client.phone.present?
          %td
            .dropdown.text-center
            %a#dropdownMenuLink{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
              = material_icon.more_vert
            .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
              = link_to("Edit", edit_admin_client_path(client), class: 'dropdown-item')
              - if client.deleted_at.present?
                = button_to "Enable User", {controller: "clients", action: "reactivate_client", id: client.id}, {class: 'dropdown-item', data: { :confirm => "Are you sure?" }}
              -else
                = link_to("Disable User", admin_client_path(client), data: { confirm: "Are you sure?" }, method: :delete, class: 'dropdown-item')
              = link_to("Reset password", admin_send_reset_password_instructions_path(client), data: { confirm: "Are you sure?" }, method: :post, class: 'dropdown-item')

app/views/admin/clients/_form.html.haml
= simple_form_for [:admin, @client] do |f|
  = render 'shared/errors', object: @client
  - if @client.new_record?
    = f.simple_fields_for :client_info do |f|
      = f.input :company_id, collection: Company.all
  = render 'admin/shared/form_nested', f: f
  .form-group
    = f.submit @client.new_record? ? "Create User" : "Update User", :class => 'btn btn-primary'

app/views/admin/clients/edit.html.haml
%h1 Edit User
.container-content
  = render 'form'

app/views/admin/clients/new.html.haml
%h1 New Client
.container-content
  = simple_form_for [:admin, @client] do |f|
    = f.simple_fields_for :client_info do |f|
      = f.input :company_id, collection: Company.all
    = render 'admin/shared/form_nested', f: f
    .form-group
      = f.submit 'Create New', :class => 'btn btn-primary'