config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path:       '',
             controllers: { invitations: 'users/invitations' },
             path_names: {
               sign_in:      'login',
               sign_out:     'logout',
               password:     'secret',
               confirmation: 'verification',
               unlock:       'unblock',
             }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    post 'users/:id/reactivate_user' => 'users#reactivate_user', as: :reactivate_user
    post 'users/:id/send_reset_password_instructions' => 'users#send_reset_password_instructions', as: :send_reset_password_instructions
    get 'reactivate_user'
    resources :mentors do
      get :track_mentor_time, controller: 'time_trackings'
    end
    post 'mentors/:id/reactivate_mentor' => 'mentors#reactivate_mentor', as: :reactivate_mentor
    get 'reactivate_mentor'
    resources :admins
    post 'admins/:id/reactivate_admin' => 'admins#reactivate_admin', as: :reactivate_admin
    get 'reactivate_admin'
    resources :clients
    post 'clients/:id/reactivate_client' => 'clients#reactivate_client', as: :reactivate_client
    get 'reactivate_client'
    resources :tags
    resources :companies do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
      resources :time_trackings, only: :index, path: 'time-tracker'
    end
    resources :checklists
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :logs, only: :index

    get :track_company_time, controller: 'time_trackings'
    root 'companies#index'
  end

  namespace :mentor do
    root 'companies#index'
    resources :companies, only: [:index, :show] do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
    end
    resources :phases
    resources :milestones
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :time_trackings, only: [:index, :new, :create], path: 'time-tracker'
  end

  namespace :member do
    root 'dashboard#show'
    resources :companies, path: 'company', only: :show
    resources :clients
    resources :company_phases
    resources :milestones, except: [:index, :create, :new, :show, :edit, :update, :destroy] do
      put :mark_complete
      put :mark_incomplete
    end
    resources :company_tasks, only: [] do
      member do
        put :mark_complete
        put :mark_incomplete
      end
    end
  end
  resources :messages
end

app/views/shared/_companies_index.html.haml
.container.container-content
  %table.table.table-borderless.table-responsive-sm
    %thead.thead
      %tr
        %th{:scope => "col"} 
          %h6 Company 
        %th{:scope => "col"} 
          %h6 Industry
        %th{:scope => "col"} 
          %h6 Location  
        %th{:scope => "col", class: 'text-center'} 
          %h6 Phase 
        %th{:scope => "col", class: 'text-center'} 
          %h6 Progress 
        %th{:scope => "col", class: 'text-center'} 
          %h6 Time Tracking 
        %th{:scope => "col", class: 'text-center'} 
          %h6 Actions 
    %tbody
      - @companies.each do |company|
        - path = nil
        - if current_user.admin?
          - path = admin_company_company_phase_path(company, company.current_phase) if company.current_phase.present?
        - elsif current_user.mentor?
          - path = mentor_company_company_phase_path(company, company.current_phase)
        %tr.tbody-tr-border
          %td
            - if company.current_phase
              =link_to(path) do
                %img{:src => "#{company.logo}", class: "img-avatar mr-2"}
                = company.name
            - else 
              %img{:src => "#{company.logo}", class: "img-avatar mr-2"}
              = company.name
          %td= company.tags.first.name if company.tags.present?
          %td= company.location.city
          %td.text-center= company.current_phase.phase.phase_number.value if company.current_phase.present?
          %td.text-center= "#{calculate_task_progress(company.current_phase, company)}%" if company.current_phase.present?
          %td.text-center.d-flex.align-center.justify-content-around{class: "#{exceeded_quota(company.current_monthly_hours)}"}
            = company.current_monthly_hours
            - if current_user.admin?
              = link_to(admin_company_time_trackings_path(company)) do
                = material_icon.access_time
            - else
              = link_to(mentor_time_trackings_path) do
                = material_icon.access_time
          %td.text-center  
            - if current_user.admin?
              = link_to(edit_admin_company_path(company), class: 'text-muted') do
                = material_icon.edit
            - elsif current_user.mentor?
              = link_to 'View', mentor_company_company_phase_path(company, company.current_phase), class: 'btn btn-secondary btn-sm' if company.current_phase
.container.container-content
  %h4 Hours report
  = form_tag admin_track_company_time_path(format: "csv"), method: :get do
    .form-row
      .col-md-10
        = select_tag :company_id, options_for_select(Company.all.collect {|company| [company.name, company.id]}), { class: 'custom-select' }
      .col-md-2
        = submit_tag "Download", class: 'btn btn-primary', data: { disable_with: false } 

app/views/shared/_company_phase_checklists_tasks_form.html.haml
- @phase.checklists.each_with_index do |checklist, index|
  #accordionChecklist.accordion
    .card
      .card-header.d-flex.align-items-center{id: "heading-#{index}"}
        %h5.flex-grow-1.mb-0=checklist.name
        %button.btn.btn-link{"aria-controls" => "collapse-#{index}", "aria-expanded" => "true", "data-target" => "#collapse-#{index}", "data-toggle" => "collapse", type: "button"}
          = material_icon.keyboard_arrow_down
      .collapse{id: "collapse-#{index}", "aria-labelledby" => "heading-#{index}", "data-parent" => "#accordionChecklist"}
        .card-body
          %ul.list-group.list-group-flush
            %div.list-group.list-group-flush
              - checklist.tasks.each_with_index do |task, index|
                - @company_task = task.company_tasks.find_or_create_by(company: @company)
                %div.list-group-item.d-flex.justify-content-between
                  .d-flex.p-2
                    %p
                      =task.description 
                    - @company_task_complete = task.company_tasks.find_by(complete: true, company: @company)
                    - unless  @company_task_complete.nil?
                      - if @company_task_complete.approved
                        %label.text-success.ml-2 Approved
                      - else
                        -if current_user.is_a?(Admin)
                          = link_to 'Approve', admin_company_task_approve_path(company_id: @company.id, company_task_id: task.id), method: :put , class: 'ml-2'
                          %span.ml-2= "|"
                          = link_to 'Reject', admin_company_task_refuse_path(company_id: @company.id, company_task_id: task.id), method: :put , class: 'ml-2'
                        - elsif current_user.is_a?(Mentor)
                          = link_to 'Approve', mentor_company_task_approve_path(company_id: @company.id, company_task_id: task.id), method: :put , class: 'ml-2'
                          %span.ml-2= "|"
                          = link_to 'Reject', mentor_company_task_refuse_path(company_id: @company.id, company_task_id: task.id), method: :put , class: 'ml-2'
                  .mt-2
                    - if @phase == @company.current_phase
                      = link_to 'New Message', new_message_path(company_task_id: @company_task.id), data: { modal: true }
                      %span= "|"
                    - if @company_task.present?
                      %a{"aria-controls" => "collapse-comment-#{@company_task.id}", id: "trigger-comments-#{@company_task.id}", "aria-expanded" => "false", "data-toggle" => "collapse", href: "#collapse-comment-#{@company_task.id}", role: "button"}
                        Comments
                        %b="(#{@company_task.messages.count})"
                .collapse{id: "collapse-comment-#{@company_task.id}"}
                  %div{ id: "messages-#{@company_task.id}" }
                    - if @company_task.messages.present?
                      - @company_task.messages.each do |message|
                        =render 'messages/message', message: message
                    - else
                      %blockquote.blockquote.text-center
                        %p.mt-3 No comments to display

app/views/shared/_company_phase_learning_objectives_form.html.haml
= form.fields_for :phase do |f|
  .form-group
    = f.trix_editor :learning_objectives
.form-group
  = form.submit 'Save Learning Objectives', :class => 'btn btn-primary'

app/views/shared/_company_phase_milestone_fields.html.haml
.nested-fields.form-row
  .form-group.col-md-10
    = f.input :title, label: false
  - if f.object.approved
    .form-group.col-md-2
      %p.text-success.text-center
        Approved
  -else
    .form-group.col-md-2
      .form-group
        = link_to_remove_association 'Remove', f, class: 'form-control btn btn-danger'
    - if f.object.complete
      .form-group.mr-1
        = link_to 'Approve', admin_milestone_approve_path(milestone_id: f.object.id), method: :put , class: 'form-control btn btn-success ml-1' if  current_user.admin?
        = link_to 'Approve', mentor_milestone_approve_path(milestone_id: f.object.id), method: :put , class: 'form-control btn btn-success ml-1' if  current_user.mentor?
      .form-group
        = link_to 'Reject', admin_milestone_refuse_path(milestone_id: f.object.id), method: :put , class: 'form-control btn btn-danger ml-1' if current_user.admin?
        = link_to 'Reject', mentor_milestone_refuse_path(milestone_id: f.object.id), method: :put , class: 'form-control btn btn-danger ml-1' if current_user.mentor?

app/views/shared/_company_phase_milestones_form.html.haml
= link_to_add_association 'Add milestone', form, :milestones, partial: 'shared/company_phase_milestone_fields', class: "btn btn-secondary mb-4"
= form.simple_fields_for :milestones do |f|
  = render 'shared/company_phase_milestone_fields', f: f
.form-group
  = form.submit 'Save Milestones', :class => 'btn btn-primary mt-4'

app/views/shared/_company_phase_show.html.haml
= render 'shared/company_phase_title_row'
.row
  .mt-4.col-12.bg-white.border-light-gray.ac-corner-radius.p-4
    = form_for [current_user.class.to_s.downcase.to_sym, @company, @phase] do |form|
      %h5.mb-3= "Learning Objectives"
      - if current_user.admin?
        %p
          %mark="Editing this learning objective will modify all the companies on Phase #{@phase.phase.id} "
        %div
          = render 'shared/company_phase_learning_objectives_form', form: form
      - else
        = @phase.phase.learning_objectives.html_safe if @phase.phase.learning_objectives.present?
        %p= 'No learning objective defined yet.' if @phase.phase.learning_objectives.present? == false
  .mt-4.col-12.bg-white.border-light-gray.ac-corner-radius.p-4
    = simple_form_for [current_user.class.to_s.downcase.to_sym, @company, @phase] do |form|
      %h5.mb-3= "Milestones"
      %div
        = render 'shared/company_phase_milestones_form', form: form
  .mt-4.col-12.bg-white.border-light-gray.ac-corner-radius.p-4.mb-4
    %h5.mb-3= "Checklists"
    = render 'shared/company_phase_checklists_tasks_form'

app/views/shared/_company_phase_title_row.html.haml
.row
  .mt-4.col-md-7.col-sm.bg-white.border-light-gray.ac-corner-radius
    .row
      .col-3
        %img.img-fluid.p-4{src: @company.logo}
      .col-9.p-4
        %h5= @company.name
        %span.d-block= "Sara Coivisto"
        %span.d-block= @company.description
  .mt-4.col-1
  .mt-4.col-sm.col-md-4.bg-white.border-light-gray.ac-corner-radius.my-auto
    .row.p-4
      .col.text-center.my-auto
        %div
          %h6= "PHASE"
        %div
          %h2= @phase.phase.phase_number.value
      .col.h-100.my-auto
        - progress = calculate_task_progress(@phase, @company)
        .progress{"data-percentage" => "#{progress}"}
          %span.progress-left
            %span.progress-bar
          %span.progress-right
            %span.progress-bar
          .progress-value
            %div
              %h2.text-center.h-100.my-auto
                = "#{progress}%"

app/views/shared/_errors.html.haml
- if object.errors.any?
  #error_explanation.alert.alert-danger.alert-dismissible.fade.show{role: "alert"}
    %h4
      = pluralize(object.errors.count, "error")
      prohibited
      this 
      = object.model_name 
      from being saved:
    %ul
      - object.errors.full_messages.each do |msg|
        %li{ class: 'list-unstyled' }= msg
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×

app/views/shared/_flash.html.haml
- flash.each do |type, msg|
  %div{:class => "alert #{bootstrap_class_for_flash(type)} alert-dismissable fade show"}
    = msg
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×

app/views/shared/_nav_links.html.haml
- if current_user.present? && current_user.admin?
  %li.nav-item
    = link_to 'Clients' , admin_root_path, class: "nav-link"
  %li.nav-item
    = link_to 'Users' , admin_users_path, class: "nav-link"
  %li.nav-item
    = link_to 'Checklists' , admin_checklists_path, class: "nav-link"
  %li.nav-item
    = link_to 'Tags' , admin_tags_path, class: "nav-link"
  %li.nav-item
    = link_to 'Activity', admin_logs_path, class: "nav-link"
- elsif current_user.present? && current_user.mentor?   
  %li.nav-item.dropdown
    = link_to 'Dashboard' , mentor_root_path, class: "nav-link"
  %li.nav-item
    = link_to 'Time Tracker', mentor_time_trackings_path, class: "nav-link"
- elsif current_user.present? && current_user.client?
  %li.nav-item.dropdown
    = link_to 'Dashboard' , member_root_path, class: "nav-link"
  %li.nav-item
    = link_to 'Invite Members' , new_member_client_path, class: "nav-link"

app/views/shared/_table.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th{:scope => "col"} Email
      %th{:scope => "col"} Role
      %th{:scope => "col"} Delete
  %tbody
    - obj.each do |user|
      %tr
        %td
          = link_to user.email, [:admin, user]
        %td
          = user.type
        %td
          = link_to("Delete user", admin_user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger btn-sm') unless user == current_user