config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path:       '',
             controllers: { invitations: 'users/invitations' },
             path_names: {
               sign_in:      'login',
               sign_out:     'logout',
               password:     'secret',
               confirmation: 'verification',
               unlock:       'unblock',
             }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    post 'users/:id/reactivate_user' => 'users#reactivate_user', as: :reactivate_user
    post 'users/:id/send_reset_password_instructions' => 'users#send_reset_password_instructions', as: :send_reset_password_instructions
    get 'reactivate_user'
    resources :mentors do
      get :track_mentor_time, controller: 'time_trackings'
    end
    post 'mentors/:id/reactivate_mentor' => 'mentors#reactivate_mentor', as: :reactivate_mentor
    get 'reactivate_mentor'
    resources :admins
    post 'admins/:id/reactivate_admin' => 'admins#reactivate_admin', as: :reactivate_admin
    get 'reactivate_admin'
    resources :clients
    post 'clients/:id/reactivate_client' => 'clients#reactivate_client', as: :reactivate_client
    get 'reactivate_client'
    resources :tags
    resources :companies do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
      resources :time_trackings, only: :index, path: 'time-tracker'
    end
    resources :checklists
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :logs, only: :index

    get :track_company_time, controller: 'time_trackings'
    root 'companies#index'
  end

  namespace :mentor do
    root 'companies#index'
    resources :companies, only: [:index, :show] do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
    end
    resources :phases
    resources :milestones
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :time_trackings, only: [:index, :new, :create], path: 'time-tracker'
  end

  namespace :member do
    root 'dashboard#show'
    resources :companies, path: 'company', only: :show
    resources :clients
    resources :company_phases
    resources :milestones, except: [:index, :create, :new, :show, :edit, :update, :destroy] do
      put :mark_complete
      put :mark_incomplete
    end
    resources :company_tasks, only: [] do
      member do
        put :mark_complete
        put :mark_incomplete
      end
    end
  end
  resources :messages
end

app/views/admin/admins/_admin_list.html.haml
.container.container-content
  %table.table.table-borderless.table-responsive-sm
    %thead.thead
      %tr
        %th{:scope => "col"} 
          %h6 Name
        %th{:scope => "col"} 
          %h6 Email
        %th{:scope => "col"} 
          %h6 Phone
        %th{:scope => "col"} 
          %h6.text-center Actions
    %tbody
      - @admins.each do |admin|
        %tr
          %td
            = admin.name if admin.name.present?
          %td
            = admin.email
            = " (Invitation pending)" if admin.invitation_created_at.present? && admin.invitation_accepted_at.nil?
          %td
            = admin.phone if admin.phone.present?
          %td
            .dropdown.text-center
              %a#dropdownMenuLink{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
                = material_icon.more_vert
              .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
                = link_to("Edit", edit_admin_admin_path(admin), class: 'dropdown-item')
                - if admin.deleted_at.present?
                  = button_to "Enable User", {controller: "admins", action: "reactivate_admin", id: admin.id}, {class: 'dropdown-item', data: { :confirm => "Are you sure?" }}
                -else
                  = link_to("Disable User", admin_admin_path(admin), data: { confirm: "Are you sure?" }, method: :delete, class: 'dropdown-item') unless current_user == admin
                = link_to("Reset password", admin_send_reset_password_instructions_path(admin), data: { confirm: "Are you sure?" }, method: :post, class: 'dropdown-item')

app/views/admin/admins/_form.html.haml
= simple_form_for [:admin, @admin] do |f|
  = render 'shared/errors', object: @admin
  .form-group
  = render 'admin/shared/form_nested', f: f
  .form-group
    = f.submit @admin.new_record? ? "Create Admin" : "Update Admin", :class => 'btn btn-primary'

app/views/admin/admins/edit.html.haml
%h1 Edit Administrator
.container-content
  = render 'form'

app/views/admin/admins/new.html.haml
%h1 New Administrator
.container-content
  = render 'form'