config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path:       '',
             controllers: { invitations: 'users/invitations' },
             path_names: {
               sign_in:      'login',
               sign_out:     'logout',
               password:     'secret',
               confirmation: 'verification',
               unlock:       'unblock',
             }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    post 'users/:id/reactivate_user' => 'users#reactivate_user', as: :reactivate_user
    post 'users/:id/send_reset_password_instructions' => 'users#send_reset_password_instructions', as: :send_reset_password_instructions
    get 'reactivate_user'
    resources :mentors do
      get :track_mentor_time, controller: 'time_trackings'
    end
    post 'mentors/:id/reactivate_mentor' => 'mentors#reactivate_mentor', as: :reactivate_mentor
    get 'reactivate_mentor'
    resources :admins
    post 'admins/:id/reactivate_admin' => 'admins#reactivate_admin', as: :reactivate_admin
    get 'reactivate_admin'
    resources :clients
    post 'clients/:id/reactivate_client' => 'clients#reactivate_client', as: :reactivate_client
    get 'reactivate_client'
    resources :tags
    resources :companies do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
      resources :time_trackings, only: :index, path: 'time-tracker'
    end
    resources :checklists
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :logs, only: :index

    get :track_company_time, controller: 'time_trackings'
    root 'companies#index'
  end

  namespace :mentor do
    root 'companies#index'
    resources :companies, only: [:index, :show] do
      resources :company_phases, except: [:new, :create, :destroy], path: 'phase'
    end
    resources :phases
    resources :milestones
    resources :company_tasks, only: [] do
      put :approve
      put :refuse
    end
    resources :milestones, only: [] do
      put :approve
      put :refuse
    end
    resources :time_trackings, only: [:index, :new, :create], path: 'time-tracker'
  end

  namespace :member do
    root 'dashboard#show'
    resources :companies, path: 'company', only: :show
    resources :clients
    resources :company_phases
    resources :milestones, except: [:index, :create, :new, :show, :edit, :update, :destroy] do
      put :mark_complete
      put :mark_incomplete
    end
    resources :company_tasks, only: [] do
      member do
        put :mark_complete
        put :mark_incomplete
      end
    end
  end
  resources :messages
end

app/models/mentor.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  phone                  :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  deleted_at             :datetime
#  type                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :bigint(8)
#  invitations_count      :integer          default(0)
#

class Mentor < User
  has_many :time_trackings
  has_many :companies
  has_many :has_tags, dependent: :destroy
  has_many :tags, through: :has_tags
  has_one :mentor_info, dependent: :destroy

  after_create_commit :create_mentor_info

  accepts_nested_attributes_for :mentor_info

  def current_monthly_hours
    total = time_trackings.where('extract(month from date) = ?', Time.now.month)
    total.map(&:hours_spent).sum
  end

  def company_monthly_hours(company)
    total = time_trackings.where(["extract(month from date) = ? and company_id = ?", Time.now.month, company.id])
    total.map(&:hours_spent).sum
  end

  private

  def create_mentor_info
    self.mentor_info = MentorInfo.create(is_active: true) if mentor_info.nil?
  end
end

app/controllers/admin/mentors_controller.rb
class Admin::MentorsController < Admin::UsersController
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: :show
  before_action :set_mentor, only: [:edit, :update, :show]

  def new
    @mentor = Mentor.new
    @mentor.build_mentor_info
  end

  def create
    @mentor = Mentor.new(mentor_params)
    @mentor.skip_password_validation = true
    if @mentor.valid?
      @mentor.save
      @mentor.invite!(current_user)
      redirect_to(admin_users_path, notice: 'Mentor was successfully created.')
    else
      render action: :new
    end
  end

  def show; end

  def destroy
    @mentor = Mentor.find(params[:id])
    @mentor.soft_delete
    redirect_to admin_users_path, notice: "Mentor deleted."
  end

  def reactivate_mentor
    @user = Mentor.find(params[:id])
    @user.update_attribute(:deleted_at, nil)
    flash[:notice] = "Mentor Activated succesfully"
    redirect_to admin_users_path
  end

  def edit
    build_has_tags
  end

  def update
    if @mentor.update(mentor_params)
      redirect_to(admin_users_path, notice: 'Mentor was successfully updated.')
    else
      render :edit
    end
  end

  private

  def set_mentor
    @mentor ||= Mentor.find(params[:id])
  end

  def mentor_params
    params.require(:mentor).permit(user_params, tag_ids: [])
  end

  def build_has_tags
    Tag.all.each do |tag|
      @mentor.has_tags.build(tag_id: tag.id)
    end
  end
end

app/controllers/mentor/companies_controller.rb
class Mentor::CompaniesController < Mentor::MentorBaseController
  before_action :set_company, only: [:show]

  def index
    @companies = Company.all
  end

  def show
    @location = @company.location
    @phase = @company.company_phases.with_status(:active).first
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end
end

app/controllers/mentor/company_phases_controller.rb
class Mentor::CompanyPhasesController < Mentor::MentorBaseController
  before_action :set_company
  before_action :set_phase, only: [:show, :edit, :update]
  before_action :set_message, only: [:show, :edit, :update]

  layout 'phase/application'

  def index
    @phase = CompanyPhase.where.not(["company_phases.status = ? and company_id = ?", CompanyPhase.statuses[:inactive], @company.id])
  end

  def show
    @phases = @company.company_phases
  end

  def edit; end

  def update
    @phase.update(phase_params)
    redirect_to(mentor_company_company_phase_path, notice: 'Company was successfully updated.')
  end

  private

  def set_phase
    @phase ||= CompanyPhase.find(params[:id])
  end

  def set_company
    @company ||= Company.find(params[:company_id])
  end

  def set_message
    @message = Message.new
  end

  def phase_params
    params.require(:company_phase).permit(milestones_attributes: [:id, :title], phase_attributes: [:id, :learning_objectives])
  end
end

app/controllers/mentor/company_tasks_controller.rb
class Mentor::CompanyTasksController < Mentor::MentorBaseController
  before_action :set_company_task

  def approve
    @task.update_attribute(:approved, true)
    Log.create(loggable: @task, description: 'Task approved', user: current_user)
    @task.company.clients.each do |client|
      NotificationMailer.task_approved_notification(client, current_user, @task).deliver_later
    end
    flash[:notice] = "Task approved"
    redirect_to mentor_company_company_phase_path(@task.company, @task.company.current_phase)
  end

  def refuse
    @task.update_attributes(approved: false, complete: false)
    Log.create(loggable: @task, description: 'Task rejected', user: current_user)
    @task.company.clients.each do |client|
      NotificationMailer.task_refused_notification(client, current_user, @task).deliver_later
    end
    flash[:notice] = "Task rejected"
    redirect_to mentor_company_company_phase_path(@task.company, @task.company.current_phase)
  end

  private

  def set_company_task
    @task = CompanyTask.find_by(company_id: params[:company_id].to_i, task_id: params[:company_task_id].to_i)
  end
end

app/controllers/mentor/dashboard_controller.rb
class Mentor::DashboardController < Mentor::MentorBaseController
  def show; end
end

app/controllers/mentor/mentor_base_controller.rb
class Mentor::MentorBaseController < ApplicationController
  before_action :authenticate_mentor!
  def authenticate_mentor!
    return if user_signed_in? && current_user.mentor?

    flash[:error] = "You don't have the permissions to do this!"
    redirect_to root_path
  end
end

app/controllers/mentor/milestones_controller.rb
class Mentor::MilestonesController < Mentor::MentorBaseController
  before_action :set_milestone

  def approve
    @milestone.update_attribute(:approved, true)
    Log.create(loggable: @milestone, description: 'Milestone approved', user: current_user)
    @milestone.company_phase.company.clients.each do |client|
      NotificationMailer.milestone_approved_notification(client, current_user, @milestone).deliver_later
    end
    redirect_to mentor_company_company_phase_path(@milestone.company_phase.company, @milestone.company_phase)
  end

  def refuse
    @milestone.update_attributes(approved: false, complete: false)
    Log.create(loggable: @milestone, description: 'Milestone rejected', user: current_user)
    @milestone.company_phase.company.clients.each do |client|
      NotificationMailer.milestone_refused_notification(client, current_user, @milestone).deliver_later
    end
    redirect_to mentor_company_company_phase_path(@milestone.company_phase.company, @milestone.company_phase)
  end

  private

  def set_milestone
    @milestone = Milestone.find(params[:milestone_id])
  end
end

app/controllers/mentor/time_trackings_controller.rb
class Mentor::TimeTrackingsController < Mentor::MentorBaseController
  def index
    @time_trackings = current_user.time_trackings
    respond_to do |format|
      format.html
      format.csv { 
        send_data @time_trackings.to_csv(['Date', 'Hours Spent', 'Company', 'Mentor', 'Notes']),
        filename: "#{current_user.name}-#{Date.today}.csv"
      }
    end
  end

  def new
    @time_tracking = current_user.time_trackings.new
  end

  def create
    @time_tracking = current_user.time_trackings.new(time_tracking_params)
    if @time_tracking.save
      redirect_to(mentor_time_trackings_path, notice: 'Time Tracking was successfully created.')
    else
      render :new
    end
  end

  private

  def time_tracking_params
    params.require(:time_tracking).permit(:hours_spent, :date, :notes, :company_id)
  end
end

app/views/admin/mentors/_form.html.haml
= render 'shared/errors', object: @mentor
= render 'admin/shared/form_nested', f: f

app/views/admin/mentors/_mentor_list.html.haml
.container.container-content
  %table.table.table-borderless.table-responsive-sm
    %thead.thead
      %tr
        %th{:scope => "col"} 
          %h6 Name
        %th{:scope => "col"} 
          %h6 Email
        %th{:scope => "col"} 
          %h6 Phone
        %th.text-center{:scope => "col"} 
          %h6 Time Tracking
        %th{:scope => "col"} 
          %h6.text-center Actions
    %tbody
      - @mentors.each do |mentor|
        %tr
          %td
            = mentor.name if mentor.name.present?
          %td
            = mentor.email
            = " (Invitation pending)" if mentor.invitation_created_at.present? && mentor.invitation_accepted_at.nil?
          %td
            = mentor.phone if mentor.phone.present?
          
          %td.text-center.d-flex.align-center.justify-content-around{class: "#{exceeded_quota(mentor.current_monthly_hours)}"}
            %p= mentor.current_monthly_hours
            = link_to(admin_mentor_path(mentor)) do
              = material_icon.access_time
          %td
            .dropdown.text-center
              %a#dropdownMenuLink{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
                = material_icon.more_vert
              .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
                = link_to("Edit", edit_admin_mentor_path(mentor), class: 'dropdown-item')
                = link_to "Download report", admin_mentor_track_mentor_time_path(mentor, format: "csv"), class: 'dropdown-item'
                - if mentor.deleted_at.present?
                  = button_to "Enable User", {controller: "mentors", action: "reactivate_mentor", id: mentor.id}, {class: 'dropdown-item', data: { :confirm => "Are you sure?" }}
                -else
                  = link_to("Disable User", admin_mentor_path(mentor), data: { confirm: "Are you sure?" }, method: :delete, class: 'dropdown-item') unless mentor == current_user
                = link_to("Reset password", admin_send_reset_password_instructions_path(mentor), data: { confirm: "Are you sure?" }, method: :post, class: 'dropdown-item')

            

app/views/admin/mentors/edit.html.haml
%h1 Edit Mentor
.container-content
  = simple_form_for [:admin, @mentor] do |f|
    = render 'form', f: f
    .form-group.row
      .col-sm-2 Expertise Tags
      .col-sm-10
        - Tag.all.where(tag_type: 'expertise').each do |tag|
          .form-check.form-check-inline.custom-checkbox.p-2
            = check_box_tag 'mentor[tag_ids][]', tag.id, @mentor.tags.include?(tag), id: dom_id(tag), class: "custom-control-input", type: "checkbox"
            = label_tag dom_id(tag), tag.name, class: "custom-control-label"
    .form-group
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/admin/mentors/new.html.haml
%h1 New Mentor
.container-content
  = simple_form_for [:admin, @mentor] do |f|
    = render 'form', f: f
    .form-group.row
      .col-sm-2 Expertise Tags
      .col-sm-10
        - Tag.all.where(tag_type: 'expertise').each do |tag|
          .form-check.form-check-inline.custom-checkbox
            = check_box_tag 'mentor[tag_ids][]', tag.id, @mentor.tags.include?(tag), id: dom_id(tag), class: "custom-control-input", type: "checkbox"
            = label_tag dom_id(tag), tag.name, class: "custom-control-label"
    .form-group
      = f.submit 'Create New', :class => 'btn btn-primary'

app/views/admin/mentors/show.html.haml
%h1 Hours logged
.container.container-content
  %table.table.table-borderless.table-responsive-sm{id: ""}
    %thead
      %tr
        %th Date
        %th Hours Spent
        %th Notes
        %th Company
    %tbody#topics
      - @mentor.time_trackings.each do |time_tracking|
        %tr{id: "log-#{time_tracking.id}"}
          %td= time_tracking.date
          %td= time_tracking.hours_spent
          %td= time_tracking.notes
          %td= time_tracking.company.name
      %td Current Monthly Hours
      %td= @mentor.current_monthly_hours
      %td
      %td